### ISSUE TITLE
Exception while Nikto scanning "Obscurity"

### ISSUE THREAD

**Issue by kdirectorate** [calebstewart/python-htb#3]
htb machine scan

[-] beginning nikto scan on 8080/tcp (http-proxy)
- Nikto v2.1.6
---------------------------------------------------------------------------
+ Target IP:          10.10.10.168
+ Target Hostname:    obscurity.htb
+ Target Port:        8080
+ Start Time:         2020-03-25 11:44:16 (GMT-5)
---------------------------------------------------------------------------
+ Server: BadHTTPServer
+ The anti-clickjacking X-Frame-Options header is not present.
+ The X-XSS-Protection header is not defined. This header can hint to the user agent to protect against some forms of XSS
+ The X-Content-Type-Options header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type
+ No CGI Directories found (use '-C all' to force check all possible dirs)
+ Web Server returns a valid response with junk HTTP methods, this may cause false positives.
+ ERROR: Error limit (20) reached for host, giving up. Last error: error reading HTTP response
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/htb/scanner/scanner.py", line 191, in _do_background_scan
    tracker.events.put(tracker)
AttributeError: 'NoneType' object has no attribute 'put'

**Comment by calebstewart** [comment]
This is the same problem as the other issue. Is this tested with the newest push of the code from a earlier today (referenced in other issue).

**Comment by calebstewart** [comment]
Duplicate of #2

**Comment by kdirectorate** [comment]
Yes, its fixed now.
