### ISSUE TITLE
Where can I find my api token?

### ISSUE THREAD

**Issue by saarsc** [calebstewart/python-htb#5]
Hi,
When I try to do anything I keep getting the error AuthFailure. 

I did provide email and password, but not the token mainly because well... I can't find where I get it from 

Love the idea of this hoping you could help me so I could actually use it :)

Thank you

**Comment by Ferdyverse** [comment]
Hi, just login at https://www.hackthebox.eu go to  your settings (click on avatar top right) and scroll down. You will find it.

**Comment by saarsc** [comment]
Thank you! 

seemed like it should be in the access pane(where I looked) but I guess not
